---
apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      version: cute
      app: name-service
    name: servicemesh-cute-service
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "true"
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/scheme: "http"
          kiali.io/runtimes: "thorntail"
        labels:
          version: cute
          app: name-service
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: cute-name:latest
          imagePullPolicy: Always
          name: thorntail
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - thorntail
        from:
          kind: ImageStreamTag
          name: cute-name:latest
      type: ImageChange
