apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: name-service
spec:
  host: name-service
  subsets:
  - name: boring
    labels:
      version: boring
  - name: cute
    labels:
      version: cute
